### ISSUE TITLE
ignore配置没有生效

### ISSUE THREAD

**Issue by zciyi** [chendaleiQ/vite-oss-upload#1]
ignore配置没有生效
看代码写了判断
if (ignore) {
    if (ssrClient) {
      return ['**/ssr-manifest.json', '**/*.html', ...ignore]
    }
    if (ssrServer) {
      return ['**']
    }
  }
期望ignore 配置数组能生效

**Comment by chendaleiQ** [comment]
好的，谢谢反馈
